# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.245.0/containers/python-3/.devcontainer/base.Dockerfile

ARG VARIANT="3.12"
FROM mcr.microsoft.com/vscode/devcontainers/python:${VARIANT}